import asyncio
from typing import Dict, List
from ...core.domain.models import AnalysisResult, SentimentResult, LLMAnalysisResult, NewsImpactAnalysis, NewsArticle, TrendingTopic
from ...core.domain.enums import SignalType, Sentiment
from ...core.interfaces.llm_provider import ILLMProvider

class MockLLMProvider(ILLMProvider):
    """
    A mock LLM Provider useful for testing or when no valid API keys are available.
    Returns static/dummy responses instead of calling a real LLM API.
    """
    
    async def analyze_stock(self, context_data: Dict) -> LLMAnalysisResult:
        # Simulate network delay
        await asyncio.sleep(0.5)
        
        return LLMAnalysisResult(
            summary="Mock analysis: Technicals look somewhat favorable with positive news sentiment.",
            signal=SignalType.BUY,
            confidence=0.7,
            reasoning="This is a mocked LLM analysis. Based on the mock parameters, the technicals look somewhat favorable, and the mock news sentiment is positive.",
            key_levels={"support_1": 145.0, "resistance_1": 155.0},
            provider="Mock"
        )
        
    async def analyze_sentiment(self, texts: List[str]) -> SentimentResult:
        await asyncio.sleep(0.2)
        
        return SentimentResult(
            overall_sentiment=Sentiment.BULLISH,
            score=0.5,
            key_themes=["Mocked theme 1", "Mocked theme 2"],
            bullish_factors=["Mocked bullish factor: Positive market outlook"],
            bearish_factors=[]
        )

    async def analyze_article_sentiments(self, articles: List[Dict]) -> List[Dict]:
        await asyncio.sleep(0.1)
        sentiments = ["BULLISH", "NEUTRAL", "BEARISH"]
        scores = [0.5, 0.0, -0.5]
        categories = ["MARKET", "COMPANY", "MACRO"]
        return [
            {
                "index": i,
                "sentiment": sentiments[i % 3],
                "score": scores[i % 3],
                "category": categories[i % 3],
                "keywords": ["mock", "stock", "news"],
                "relevance_score": 0.7,
            }
            for i in range(len(articles))
        ]

    async def analyze_news_impact(self, symbol: str, articles: List[NewsArticle]) -> NewsImpactAnalysis:
        await asyncio.sleep(0.3)
        return NewsImpactAnalysis(
            impact_score=0.6,
            price_impact_prediction="Short-term upside potential",
            confidence=0.75,
            reasoning=f"Mocked impact analysis for {symbol} based on {len(articles)} articles. The general tone is positive.",
            affected_sectors=["Technology", "Consumer Discretionary"]
        )

    async def extract_trending_topics(self, articles: List[Dict], limit: int = 5) -> List[TrendingTopic]:
        await asyncio.sleep(0.2)
        topics = [
            TrendingTopic(topic="AI Revolution", mention_count=15, sentiment=Sentiment.BULLISH, related_symbols=["NVDA", "MSFT"]),
            TrendingTopic(topic="Fed Rate Hawks", mention_count=10, sentiment=Sentiment.BEARISH, related_symbols=["SPY"]),
            TrendingTopic(topic="Crypto Regulation", mention_count=8, sentiment=Sentiment.NEUTRAL, related_symbols=["BTC", "COIN"]),
            TrendingTopic(topic="Earnings Season", mention_count=6, sentiment=Sentiment.BULLISH, related_symbols=["AAPL", "GOOGL"]),
            TrendingTopic(topic="Oil Supply Concerns", mention_count=4, sentiment=Sentiment.BEARISH, related_symbols=["XOM"]),
        ]
        return topics[:limit]

    async def generate_report(self, analysis: AnalysisResult) -> str:
        await asyncio.sleep(0.1)
        return "# Mock Analysis Report\n\nThis report was generated by the MockLLMProvider."
